name: Create Weekly Meta Hours Discussion

on:
  schedule:
    # Runs at 00:00 UTC every Sunday
    - cron: '0 0 * * 0'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  create-discussion:
    runs-on: ubuntu-latest
    permissions:
      discussions: write
    
    steps:
      - name: Get current date
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "number=$(date +'%V')" >> $GITHUB_OUTPUT

      - name: Create discussion
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { date, number } = process.env;
            
            await github.rest.discussions.create({
              owner: context.repo.owner,
              repo: context.repo.name,
              title: `Meta_Hours_${number}`,
              body: `# Meta Hours Discussion for Week ${number} (${date})

              Please add your notes for this week's Meta Hours by Tuesday.
              
              ## Guidelines:
              - Share your key accomplishments from last week
              - Outline your plans for this week
              - Highlight any blockers or challenges
              - Mention if you need help from the team
              
              Remember: All notes should be added by Tuesday!`,
              category_id: '${{ vars.DISCUSSION_CATEGORY_ID }}'
            });
